### PR TITLE
Send the notification email after a payment

### PR DESCRIPTION
**Pull request by dikiyforester**
First commit formats the code according WP Standards
Second commit implements the notifications.

Note: reviewing code is better starting from the second commit to avoid formatting noise.
Note2: dynamic tags replacement ignores tag `{coupon_code}` since it's not implemented yet. Don't know if it will be.

### CODE REVIEW

**Comment by Arsenal21** [comment]
Nice.

**Comment by Arsenal21** [comment]
There is a little bug with the saving of the "From Email Address" field. That field needs to be able to save a value like the following:

Test Site Alpha <sales@domain.com>

At the moment, it strips the "<sales@domain.com>" value from that field when you hit "save" in the email settings menu.

**Comment by dikiyforester** [comment]
@Arsenal21 it strips anything in `<>` as unwanted HTML strings. 
I see the issue, this shouldn't be done for "From Email Address" field since it used in email headers and should come in brackets.

I'll fix it.

**Comment by dikiyforester** [comment]
Fixed via ce1fa3c

**Pull request merged**
